HAI 1.2

OBTW I NO DEECLAIR EVARY THINS AS NUMBR
BUD ITZ GUD TO DUH IT
DHA LINK TO SUBMANSION - https://www.hackerrank.com/challenges/solve-me-first/submissions/code/53485582
TLDR

I HAS A NUMBA
I HAS A NUMBU

GIMMEH NUMBA
GIMMEH NUMBU

VISIBLE SUM OF NUMBA AN NUMBU

KTHXBYE
