#!/bin/python3

import sys

def result(x,ar):
    d1=d2 = 0
    for i in range(x):
        d1+=ar[i][i]
        d2+=ar[i][x-i-1]
    return abs(d1-d2)
        

n = int(input().strip())
a = []
for a_i in range(n):
    a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
    a.append(a_t)
print(result(n, a))